src/Areas/Picnic/Controllers/ContentController.cs
using System.Threading.Tasks;
using ctorx.Core.Mvc.Messaging;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Picnic.Model;
using Picnic.Service;

namespace Picnic.Areas.Picnic.Controllers
{
    [Area("Picnic")]
    [Route("content")]
    [Authorize("PicnicAuthPolicy")]
    public class ContentController : Controller
    {
        readonly IMessenger Messenger;
        readonly IContentService ContentService;

        /// <summary>
        /// ctor the Mighty
        /// </summary>
        public ContentController(IMessenger messenger, IContentService contentService)
        {
            this.Messenger = messenger;
            this.ContentService = contentService;
        }
        

        [Route("")]
        public async Task<IActionResult> List()
        {
            var allContent = await this.ContentService.GetAllItemsAsync();
            return this.View(allContent);
        }

        [HttpGet]
        [Route("new")]
        public IActionResult New()
        {
            return this.View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("new")]
        public async Task<IActionResult> New(Content content)
        {
            var keyInUse = false;
            if (this.ModelState.IsValid)
            {
                if (!(keyInUse = this.ContentService.KeyInUse(content.Key)))
                {
                    await this.ContentService.SaveAsync(content);
                    this.Messenger.ForwardSuccess();
                    return this.RedirectToAction(nameof(Edit), new { id = content.Id });
                }
            }

            this.Messenger.AppendError(keyInUse ? "The provided content key is already being used" : null, "Error");
            return this.View(content);
        }

        [HttpGet]
        [Route("{id}/edit")]
        public async Task<IActionResult> Edit(string id)
        {
            var content = await this.ContentService.GetByIdAsync(id);

            if (content == null)
                return this.NotFound();

            return this.View(content);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("{id}/edit")]
        public async Task<IActionResult> Edit(Content content)
        {
            var keyInUse = false;
            if (this.ModelState.IsValid)
            {
                if (!(keyInUse = this.ContentService.KeyInUse(content.Key, content.Id)))
                {
                    await this.ContentService.SaveAsync(content);
                    this.Messenger.ForwardSuccess();
                    return this.RedirectToAction(nameof(Edit), new {id = content.Id});
                }
            }

            this.Messenger.AppendError(keyInUse ? "The provided content key is already being used" : null, "Error");
            return this.View(content);
        }
    }
}

src/Areas/Picnic/Controllers/PageController.cs
using System.Threading.Tasks;
using ctorx.Core.Mvc.Messaging;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Picnic.Model;
using Picnic.Service;

namespace Picnic.Areas.Picnic.Controllers
{
    [Area("Picnic")]
    [Route("pages")]
    [Authorize("PicnicAuthPolicy")]
    public class PageController : Controller
    {
        readonly IMessenger Messenger;
        readonly IPageService PageService;

        /// <summary>
        /// ctor the Mighty
        /// </summary>
        public PageController(IMessenger messenger, IPageService pageService)
        {
            this.Messenger = messenger;
            this.PageService = pageService;
        }

        [Route("")]
        public async Task<IActionResult> List()
        {
            var allPages = await this.PageService.GetAllItemsAsync();
            return this.View(allPages);
        }

        [HttpGet]
        [Route("new")]
        public IActionResult New()
        {
            return this.View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("new")]
        public async Task<IActionResult> New(Page page)
        {
            var pathInUse = false;

            page.Path = this.PageService.NormalizePath(page.Path);

            if (this.ModelState.IsValid && !string.IsNullOrWhiteSpace(page.Path))
            {
                if (!(pathInUse = await this.PageService.PathInUseAsync(page.Path, page.Id)))
                {
                    await this.PageService.SaveAsync(page);
                    this.Messenger.ForwardSuccess();
                    return this.RedirectToAction(nameof(Edit), new {id = page.Id});
                }
            }

            this.Messenger.AppendError(pathInUse ? "The provided path is already being used" : null, "Error");
            return this.View(page);
        }

        [HttpGet]
        [Route("{id}/edit")]
        public async Task<IActionResult> Edit(string id)
        {
            var page = await this.PageService.GetByIdAsync(id);

            if (page == null)
                return this.NotFound();

            return this.View(page);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("{id}/edit")]
        public async Task<IActionResult> Edit(Page page)
        {
            var pathInUse = false;

            page.Path = this.PageService.NormalizePath(page.Path);

            if (this.ModelState.IsValid && !string.IsNullOrWhiteSpace(page.Path))
            {
                if (!(pathInUse = await this.PageService.PathInUseAsync(page.Path, page.Id)))
                {
                    await this.PageService.SaveAsync(page);
                    this.Messenger.ForwardSuccess();
                    return this.RedirectToAction(nameof(Edit), new {id = page.Id});
                }
            }

            this.Messenger.AppendError(pathInUse ? "The provided path is already being used" : null, "Error");
            return this.View(page);
        }
    }
}

src/Areas/Picnic/Controllers/RootController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using ctorx.Core.Mvc.Messaging;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Picnic.Model;
using Picnic.Service;

namespace Picnic.Areas.Picnic.Controllers
{
    [Area("Picnic")]
    [Route("")]
    [Authorize("PicnicAuthPolicy")]
    public class RootController : Controller
    {
        readonly IPageService PageService;
        readonly IContentService ContentService;

        /// <summary>
        /// ctor the Mighty
        /// </summary>
        public RootController(IMessenger messenger, IPageService pageService, IContentService contentService)
        {
            this.PageService = pageService;
            this.ContentService = contentService;
        }

        [Route("")]
        public async Task<IActionResult> Index()
        {
            var model = new List<IPicnicEntity>();
            model.AddRange(await this.ContentService.GetRecentAsync(10));
            model.AddRange(await this.PageService.GetRecentAsync(10));

            return this.View(model);
        }                
    }
}

src/Areas/Picnic/Views/Shared/_CoreLayout.cshtml
@using Picnic.Areas.Picnic.Controllers
@{
	Layout = null;
}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>Picnic Content Management</title>
		
		<style type="text/css">
			@@font-face { font-family: 'Roboto';
				src: url('@Url.Static("/fonts/Roboto-Regular.ttf")') format('truetype');
			}
		</style>

		<link rel="stylesheet" href="@Url.Static("/css/picnic.min.css")" />

		@* jQuery $() Queue -- Taken from: http://writing.colin-gourlay.com/safely-using-ready-before-including-jquery/ *@
		<script>(function (w, d, u) { w.readyQ = []; w.bindReadyQ = []; function p(x, y) { if (x === "ready") { w.bindReadyQ.push(y); } else { w.readyQ.push(x); } }; var a = { ready: p, bind: p }; w.$ = w.jQuery = function (f) { if (f === d || f === u) { return a } else { p(f) } } })(window, document)</script>
		
		@* Set Root for Client *@
		<script>
			window.root = "@Url.Action(nameof(RootController.Index), "Root", new { Area = "Picnic" })";
		</script>
	</head>
	<body>		
		@RenderBody()
		
		@* Modal Containers *@
		<div id="standby" class="modal">
			<span></span>
			<img src="@Url.Static("/images/spinner.gif")" alt="" />
		</div>
 
		<!-- Alert Modal -->
		<div id="modal" class="modal">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
						<h4 class="modal-title"></h4>
					</div>
					<div class="modal-body"><p></p></div>
					<div class="modal-footer">
					</div>
				</div>
			</div>
		</div>

		<script src="@Url.Static("/js/picnic.min.js")"></script>
		
		<script id="msg-template" type="text/x-handlebars-template">
			<div class="alert alert-{{class}} alert-dismissible" role="alert">
				<button type="button" class="close" data-dismiss="alert" aria-label="Close">
					<span aria-hidden="true">×</span>
				</button> 
				<span class="glyphicon glyphicon-{{icon}}"></span> <strong>{{caption}}</strong> {{message}}
			</div>
		</script>
		
		@if (TempData["Message"] != null)
		{
			<script>
				$(function() {
					app.msg("success", "yes", "@(TempData["Message"].ToString())", false);
				});
			</script>
		}

		@* jQuery $() Queue -- Taken from: http://writing.colin-gourlay.com/safely-using-ready-before-including-jquery/ *@
		<script>
			(function ($, d) {
				$.each(readyQ, function(i, f) { $(f) });
				$.each(bindReadyQ, function(i, f) { $(d).bind("ready", f) });
			})(jQuery, document)
		</script>
	</body>
</html>

src/Areas/Picnic/Views/Shared/_Editor.cshtml
@using Microsoft.Extensions.Options;
@inject IOptions<PicnicOptions> PicnicOptionsProvider
@model string

@{
	var options = this.PicnicOptionsProvider.Value.Manage.EditorOptions;
}

<textarea id="editor" class="form-control">@Model</textarea>
<input name="image" type="file" id="tinyMceUpload" class="hidden" onchange="">

<script src="@Url.Static("/js/tinymce/tinymce.min.js")"></script>
<script>
	$(function () {
		var editorTarget = $($('form[data-editor-target]').attr('data-editor-target'));

		@if (!string.IsNullOrWhiteSpace(options.EditorBaseUrl))
		{
			<text>tinyMCE.baseURL = "@options.EditorBaseUrl";</text>
		}

		tinymce.init({
			selector: '#editor',
			theme: 'modern',
			paste_data_images: true,
			menubar: '',
			plugins: '@string.Join(" ", options.Plugins)',
			toolbar1: '@string.Join(" ", options.Buttons)',
			branding: false,
			content_css: '@string.Join(",", options.Stylesheets)',
			min_height: @options.MinHeight,
			valid_elements: '*[*]',
			force_br_newlines : false,
			force_p_newlines : false,
			forced_root_block : '',
			file_picker_callback: function(callback, value, meta) {
				if (meta.filetype === 'image') {
					$('#tinyMceUpload').trigger('click');
					$('#tinyMceUpload').on('change', function() {
						top.app.state.working();
						var file = this.files[0];
						var reader = new FileReader();
						reader.onload = function(e) {
							callback(e.target.result, { alt: '' });
							top.app.state.ready();
						};						
						reader.readAsDataURL(file);						
					});
				}
			},
			setup: function (editor) {
				editor.on("change", function(e) {
					editorTarget.val(editor.getContent());
				});
				editor.on("keyup", function(){
					editorTarget.val(editor.getContent());
				});
			}
		});
	});
</script>

src/Areas/Picnic/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.ViewEngines
@using Picnic.Areas.Picnic.Controllers
@using Picnic.PluginModel
@inject ICompositeViewEngine CompositeViewEngine

@{
	Layout = "_CoreLayout";
}

<nav class="navbar navbar-default">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="@Url.Action(nameof(RootController.Index), "Root")">Picnic</a>
		</div>
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<li><a href="@Url.Action(nameof(PageController.List), "Page")"><span class="glyphicon glyphicon-file"></span> Pages</a></li>
				<li><a href="@Url.Action(nameof(ContentController.List), "Content")"><span class="glyphicon glyphicon-pencil"></span> Content</a></li>
			</ul>						
			
			@* Render Plugin Menu Partials *@
			@foreach (var plugin in PluginManifest.GetPlugins())
			{
				var viewPath = $"~/Plugin/{plugin.Name}/_Menu.cshtml";
				if (this.CompositeViewEngine.GetView("", viewPath, false).Success)
				{
					@Html.Partial(viewPath)
				}
			}			

			<ul class="nav navbar-nav navbar-right">
				<li><a href="https://github.com/ctorx/picnic">Picnic @@ github</a></li>							
			</ul>
		</div>
	</div>
</nav>

<div class="container">
	@RenderSection("Breadcrumbs", false)			
	@Html.Partial("_MessageList")
	@RenderBody()
</div>
		

src/Areas/Picnic/Views/Shared/_MessageList.cshtml
@inject IMessenger Messenger
@using System.Collections.Generic
@using System.Threading.Tasks
@using ctorx.Core.Mvc.Messaging

@{
	var messages = this.Messenger.GetMessages();	
}

<div id="messages">
	@if (messages.Any())
	{
		<script>
			$(function() {
				@foreach (var message in messages)
				{
					var caption = message.Caption != null ? $"'{message.Caption}'" : "null";
					<text>app.msg("@message.Type", @Html.Raw(caption), "@Html.Raw(message.Text)");</text>
				}
			});
		</script>					
	}
</div>